# Generated by Django 3.2.23 on 2025-10-25 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='抽奖标题')),
                ('description', models.TextField(blank=True, verbose_name='抽奖说明')),
                ('prize_name', models.CharField(max_length=255, verbose_name='奖品名称')),
                ('prize_count', models.IntegerField(default=1, verbose_name='奖品数量')),
                ('prize_image', models.ImageField(blank=True, null=True, upload_to='prizes/', verbose_name='奖品图片')),
                ('max_participants', models.IntegerField(default=0, help_text='0表示不限制', verbose_name='最大参与人数')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('status', models.CharField(choices=[('pending', '待开始'), ('active', '进行中'), ('finished', '已结束'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '抽奖活动',
                'verbose_name_plural': '抽奖活动',
                'db_table': 'lotteries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户名')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名字')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='姓氏')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Telegram用户',
                'verbose_name_plural': 'Telegram用户',
                'db_table': 'telegram_users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_name', models.CharField(max_length=255, verbose_name='奖品名称')),
                ('won_at', models.DateTimeField(auto_now_add=True, verbose_name='中奖时间')),
                ('claimed', models.BooleanField(default=False, verbose_name='是否已领取')),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='lottery.lottery', verbose_name='抽奖活动')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_lotteries', to='lottery.telegramuser', verbose_name='中奖用户')),
            ],
            options={
                'verbose_name': '中奖记录',
                'verbose_name_plural': '中奖记录',
                'db_table': 'winners',
                'ordering': ['-won_at'],
            },
        ),
        migrations.AddField(
            model_name='lottery',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_lotteries', to='lottery.telegramuser', verbose_name='创建者'),
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participated_at', models.DateTimeField(auto_now_add=True, verbose_name='参与时间')),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='lottery.lottery', verbose_name='抽奖活动')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='lottery.telegramuser', verbose_name='参与用户')),
            ],
            options={
                'verbose_name': '参与记录',
                'verbose_name_plural': '参与记录',
                'db_table': 'participations',
                'ordering': ['-participated_at'],
                'unique_together': {('lottery', 'user')},
            },
        ),
    ]
