# Generated by Django 3.2.23 on 2025-10-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_alter_lottery_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='manual_drawn',
            field=models.BooleanField(default=False, help_text='如果手动开奖，则不会自动开奖', verbose_name='是否手动开奖'),
        ),
    ]
