# Generated by Django 3.2.23 on 2025-10-26 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0003_lottery_manual_drawn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='奖品名称')),
                ('description', models.TextField(blank=True, verbose_name='奖品描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to='prizes/', verbose_name='奖品图片')),
                ('winner_count', models.IntegerField(default=1, verbose_name='中奖人数')),
                ('level', models.IntegerField(default=1, help_text='数字越小等级越高，1=一等奖', verbose_name='奖品等级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='lottery.lottery', verbose_name='抽奖活动')),
            ],
            options={
                'verbose_name': '奖品',
                'verbose_name_plural': '奖品',
                'db_table': 'prizes',
                'ordering': ['level', 'id'],
            },
        ),
        migrations.AddField(
            model_name='winner',
            name='prize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='lottery.prize', verbose_name='中奖奖品'),
        ),
    ]
