# Generated by Django 3.2.23 on 2025-10-27 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lottery', '0005_migrate_old_prizes_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='admin_user',
            field=models.ForeignKey(blank=True, help_text='创建此抽奖的管理员账号', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_lotteries', to=settings.AUTH_USER_MODEL, verbose_name='管理员'),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_lotteries', to='lottery.telegramuser', verbose_name='Telegram创建者'),
        ),
    ]
