# Generated by Django 3.2.23 on 2025-10-28 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('lottery', '0006_auto_20251027_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('admin_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bot_config', serialize=False, to='auth.user', verbose_name='管理员')),
                ('bot_token', models.CharField(blank=True, help_text='Telegram Bot Token (从 @BotFather 获取)', max_length=255, null=True, verbose_name='Bot Token')),
                ('bot_username', models.CharField(blank=True, help_text='Bot的用户名 (例如: @MyLotteryBot)', max_length=255, null=True, verbose_name='Bot 用户名')),
                ('is_active', models.BooleanField(default=True, help_text='关闭后该Bot将停止工作', verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Bot配置',
                'verbose_name_plural': 'Bot配置',
                'db_table': 'bot_configs',
            },
        ),
    ]
