# Generated by Django 3.2.23 on 2025-10-28 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lottery', '0007_botconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, help_text='浏览器和设备信息', null=True, verbose_name='用户代理')),
                ('device_type', models.CharField(blank=True, help_text='例如：Windows, Mac, Mobile', max_length=50, null=True, verbose_name='设备类型')),
                ('browser', models.CharField(blank=True, help_text='例如：Chrome, Firefox, Safari', max_length=100, null=True, verbose_name='浏览器')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='退出时间')),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='用于关联会话', max_length=255, null=True, verbose_name='会话密钥')),
                ('is_active', models.BooleanField(default=True, verbose_name='会话是否活跃')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '登录记录',
                'verbose_name_plural': '登录记录',
                'db_table': 'login_records',
                'ordering': ['-login_time'],
            },
        ),
        migrations.AddIndex(
            model_name='loginrecord',
            index=models.Index(fields=['-login_time'], name='login_recor_login_t_40b9ed_idx'),
        ),
        migrations.AddIndex(
            model_name='loginrecord',
            index=models.Index(fields=['user', '-login_time'], name='login_recor_user_id_2826c6_idx'),
        ),
    ]
