# Generated by Django 3.2.23 on 2025-10-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0008_auto_20251028_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginrecord',
            name='last_activity',
            field=models.DateTimeField(blank=True, help_text='用户最后一次活动的时间', null=True, verbose_name='最后活动时间'),
        ),
    ]
